### ISSUE TITLE
cover failed using oci2aci

### ISSUE THREAD

**Issue by wangkirin** [huawei-openlab/oci2aci#2]
I have a complete OCI bundle and  want to covert it to aci by the oci2aci tool . But when I type following commands : `oci2aci --debug ~/runctest/` (`~/runctest/` is my OCI bundle path)，there are some errors occours :

```
root@szxbzci0040:~/gopath/src/github.com/huawei-openlab/oci2aci# oci2aci --debug ~/runctest/
2015/10/08 15:25:04 /root/runctest/: valid oci bundle
2015/10/08 15:25:10 Unmarshal runtime.json failed: json: cannot unmarshal string into Go value of type []*specs.WeightDevice
2015/10/08 15:25:10 Manifest:/tmp/oci2aci944702087/manifest generated successfully.
2015/10/08 15:25:10 Generate aci image failed:build: Layout failed validation: image manifest validation failed: missing or bad ACKind (must be "ImageManifest")
```

can anyone tell me  how to solve it ?

**Comment by ChengTiesheng** [comment]
@wangkirin according to the newest definition of oci specs,  blkioWeightDevice defined as a string is wrong. 
"blockIO": {
"blkioWeight": 0,
"blkioWeightDevice": "", --->it should be defined null

**Comment by wangkirin** [comment]
problem solved~~~
