### ISSUE TITLE
Could oci2aci provide 2 options for better use?

### ISSUE THREAD

**Issue by wangkirin** [huawei-openlab/oci2aci#3]
After using the oci2aci , I think that's a good tool for users , and could you provide the following 2 options when using the `oci2aci` command? :)
1. aci image name option: current image name/id is `example`, I think user might want to specify the name he/she wants
2. output folder:  default output folder is `/tmp` , user might want to specify where the output  `aci` file stored

**Comment by ChengTiesheng** [comment]
@wangkirin Thanks so much for your sincere advice.
Quite agree with what you said, I will implement it in the coming days.

**Comment by ChengTiesheng** [comment]
Hi @wangkirin, I have implemented what you mentioned before, please try out the tool and give your feedback, thanks a lot for your attention:-)
