### ISSUE TITLE
aci images in /tmp dir is not necessary

### ISSUE THREAD

**Issue by zenlint** [huawei-openlab/oci2aci#6]
I think it is not necessary to output the aci image both in the current dir and /tmp dir, my suggestion is to disable outputing to /tmp dir.
Thanks.

**Comment by ChengTiesheng** [comment]
Hi @zenlinTechnofreak , thanks for your sincere advice and some modification has been made for the program, just try it and give your feedback.

**Comment by zenlint** [comment]
@ChengTiesheng OK, Thanks very much.
